import { Resource } from './types';

export const resources: Resource[] = [
  {
    id: '1',
    title: 'ChatGPT Edu',
    description: 'Plataforma líder en IA conversacional adaptada para entornos educativos. Ideal para generar ideas de lecciones.',
    url: 'https://chatgpt.com',
    category: 'IA Generativa',
    tags: ['IA', 'Texto', 'Asistente'],
    imageUrl: 'https://picsum.photos/400/200?random=1',
    featured: true,
  },
  {
    id: '2',
    title: 'Canva for Education',
    description: 'Suite de diseño gráfico simplificado. Crea presentaciones, infografías y material didáctico en minutos.',
    url: 'https://www.canva.com/education/',
    category: 'Diseño',
    tags: ['Gráficos', 'Presentaciones', 'Visual'],
    imageUrl: 'https://picsum.photos/400/200?random=2',
    featured: true,
  },
  {
    id: '5',
    title: 'Midjourney',
    description: 'Generador de imágenes por IA de alta fidelidad. Perfecto para crear recursos visuales únicos para diapositivas.',
    url: 'https://midjourney.com',
    category: 'IA Generativa',
    tags: ['IA', 'Imágenes', 'Arte'],
    imageUrl: 'https://picsum.photos/400/200?random=5',
  },
  {
    id: '6',
    title: 'Genially',
    description: 'Crea contenidos interactivos y animados. Desde presentaciones hasta escapes rooms educativos.',
    url: 'https://genial.ly',
    category: 'Diseño',
    tags: ['Interactivo', 'Presentaciones', 'Animación'],
    imageUrl: 'https://picsum.photos/400/200?random=6',
  },
  {
    id: '7',
    title: 'Loom',
    description: 'Grabación de pantalla y vídeo asíncrono. Ideal para dar feedback a alumnos o grabar tutoriales rápidos.',
    url: 'https://www.loom.com',
    category: 'Multimedia',
    tags: ['Video', 'Screen Recorder', 'Feedback'],
    imageUrl: 'https://picsum.photos/400/200?random=7',
  },
  {
    id: '10',
    title: 'Synthesia',
    description: 'Crea vídeos con avatares de IA hablando en múltiples idiomas a partir de texto.',
    url: 'https://www.synthesia.io',
    category: 'IA Generativa',
    tags: ['Video', 'IA', 'Avatar'],
    imageUrl: 'https://picsum.photos/400/200?random=10',
  }
];