import { Resource } from './types';

export const resources: Resource[] = [
  {
    id: '1',
    title: 'ChatGPT Edu',
    description: 'Plataforma líder en IA conversacional adaptada para entornos educativos. Ideal para generar ideas de lecciones.',
    url: 'https://chatgpt.com',
    category: 'IA Generativa',
    tags: ['IA', 'Texto', 'Asistente'],
    imageUrl: 'https://picsum.photos/400/200?random=1',
    featured: true,
  },
  {
    id: '2',
    title: 'Canva for Education',
    description: 'Suite de diseño gráfico simplificado. Crea presentaciones, infografías y material didáctico en minutos.',
    url: 'https://www.canva.com/education/',
    category: 'Diseño',
    tags: ['Gráficos', 'Presentaciones', 'Visual'],
    imageUrl: 'https://picsum.photos/400/200?random=2',
    featured: true,
  },
  {
    id: '3',
    title: 'Kahoot!',
    description: 'Plataforma de aprendizaje basada en juegos. Crea cuestionarios interactivos para evaluar en tiempo real.',
    url: 'https://kahoot.com',
    category: 'Evaluación',
    tags: ['Gamificación', 'Quiz', 'Interactivo'],
    imageUrl: 'https://picsum.photos/400/200?random=3',
  },
  {
    id: '4',
    title: 'Notion',
    description: 'Espacio de trabajo todo en uno. Organiza temarios, bases de datos de alumnos y planificación semestral.',
    url: 'https://www.notion.so',
    category: 'Productividad',
    tags: ['Organización', 'Notas', 'Planificación'],
    imageUrl: 'https://picsum.photos/400/200?random=4',
  },
  {
    id: '5',
    title: 'Midjourney',
    description: 'Generador de imágenes por IA de alta fidelidad. Perfecto para crear recursos visuales únicos para diapositivas.',
    url: 'https://midjourney.com',
    category: 'IA Generativa',
    tags: ['IA', 'Imágenes', 'Arte'],
    imageUrl: 'https://picsum.photos/400/200?random=5',
  },
  {
    id: '6',
    title: 'Genially',
    description: 'Crea contenidos interactivos y animados. Desde presentaciones hasta escapes rooms educativos.',
    url: 'https://genial.ly',
    category: 'Diseño',
    tags: ['Interactivo', 'Presentaciones', 'Animación'],
    imageUrl: 'https://picsum.photos/400/200?random=6',
  },
  {
    id: '7',
    title: 'Loom',
    description: 'Grabación de pantalla y vídeo asíncrono. Ideal para dar feedback a alumnos o grabar tutoriales rápidos.',
    url: 'https://www.loom.com',
    category: 'Multimedia',
    tags: ['Video', 'Screen Recorder', 'Feedback'],
    imageUrl: 'https://picsum.photos/400/200?random=7',
  },
  {
    id: '8',
    title: 'Google Forms',
    description: 'Herramienta sencilla y potente para crear encuestas y exámenes autocalificables.',
    url: 'https://forms.google.com',
    category: 'Evaluación',
    tags: ['Encuestas', 'Google', 'Datos'],
    imageUrl: 'https://picsum.photos/400/200?random=8',
  },
  {
    id: '9',
    title: 'Trello',
    description: 'Gestión de proyectos visual estilo Kanban. Organiza tareas de departamento o proyectos de alumnos.',
    url: 'https://trello.com',
    category: 'Productividad',
    tags: ['Kanban', 'Gestión', 'Proyectos'],
    imageUrl: 'https://picsum.photos/400/200?random=9',
  },
  {
    id: '10',
    title: 'Synthesia',
    description: 'Crea vídeos con avatares de IA hablando en múltiples idiomas a partir de texto.',
    url: 'https://www.synthesia.io',
    category: 'IA Generativa',
    tags: ['Video', 'IA', 'Avatar'],
    imageUrl: 'https://picsum.photos/400/200?random=10',
  }
];